spring:
  datasource:
    url: jdbc:h2:mem:moodle_db
    username: admin
    password: admin
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
  h2:
    console.enabled: true
  security:
    # Secret used for signing JWT token.
    secret: moodle_secret_key_for_user_authentication
    #Validity time of JWT token in milliseconds.
    expirationTime: 36000000
  data:
    redis:
      host: localhost
      port: 6379

# Configuring the server servlet context path(add "/api" to all endpoints)
server:
  servlet:
    context-path: /api

#Credentials for basic authentication
basic:
  name: developer
  password: 123456
  role: DEVELOPER