name: Java Formatting

on:
  pull_request:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to use format on'
        required: true
        default: 'master'

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Download google-java-format
        run: wget https://github.com/google/google-java-format/releases/download/v1.16.0.2/google-java-format-1.16.0.2-all-deps.jar

      - name: Run google-java-format
        run: java -jar google-java-format-1.16.0.2-all-deps.jar --replace $(find . -name "*.java")

      - name: Print diffs
        run: git diff

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git commit -m "Apply google-java-format" || echo "No changes to commit"
          git push
