name: Java Formatting

on:
  pull_request:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to format code on'
        required: true
        default: 'master'


jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Google Java Format
        uses: google/google-java-format@latest

      - name: Format Java files
        run: |
          find . -name "*.java" | xargs google-java-format -i

      - name: Commit changes
        if: ${{ changes() }}
        run: |
          git add .
          git commit -m "Formatted Java files with Google Java Format"
