name: Google Java Format

on:
  pull_request:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to format code on'
        required: true
        default: 'main'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Google Java Format
        uses: actions/setup-java@v2
        with:
          java-version: 11

      - name: Get branch name
        id: get_branch_name
        run: echo "::set-output name=branch_name::$(github.event.inputs.branch)"

      - name: Format Java Files
        uses: google/google-java-format@latest
        args:
          --replace
          --java-version=17
          --source=.
          --target=.
          --branch=${{ steps.get_branch_name.outputs.branch_name }}

      - name: Commit Changes
        run: |
          git add -A
          git commit -m "Formatted Java files with Google Java Format"